version: "3.7"

#Docker Networks
networks:
    app-network:
        driver: bridge

services:
    app:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        image: "contact-book"
        container_name: app
        ports:
            - 8000:80
        networks:
            - app-network

    mysql:
        image: mysql:latest
        restart: always
        container_name: mysql
        ports:
            - "4306:3306"
        environment:
            MYSQL_DATABASE: "contact_book"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_ROOT_PASSWORD: ""
        networks:
            - app-network
